### ISSUE TITLE
Feature request: Expose code mirror settings

### ISSUE THREAD

**Issue by dogoku** [fkling/astexplorer#368]
Use cases for exposing CodeMirror's settings:
- Able to use a different theme (dark theme)
- Control indentation rules (current indentation is very confusing for me)
- Control font size
- ???

**Comment by dogoku** [comment]
I spent a bit of time and created a dark theme, for those that are interested.
It's based off Codemirror's Darcula theme.

To use it, you need Local Overrides enabled on Chrome, userContent.css on Firefox or the Stylish extension on either browsers.

```css
/* DARK THEME */

  /** CODEMIRROR DARCULA THEME
      Name: IntelliJ IDEA default theme
      From IntelliJ IDEA by JetBrains
   */

  .cm-s-default  { font-family: Consolas, Menlo, Monaco, 'Lucida Console', 'Liberation Mono', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', 'Courier New', monospace, serif;}
  .cm-s-default.CodeMirror, #JSONEditor .CodeMirror { background: #2B2B2B !important; color: #A9B7C6 !important; } 

  .cm-s-default span.cm-meta { color: #BBB529; }
  .cm-s-default span.cm-number { color: #6897BB; }
  .cm-s-default span.cm-keyword { color: #CC7832; line-height: 1em; font-weight: bold; }  
  .cm-s-default span.cm-def { color: #A9B7C6; font-style: italic; }
  .cm-s-default span.cm-variable { color: #A9B7C6; }
  .cm-s-default span.cm-variable-2 { color: #A9B7C6; }
  .cm-s-default span.cm-variable-3 { color: #9876AA; }
  .cm-s-default span.cm-type { color: #AABBCC; font-weight: bold; }
  .cm-s-default span.cm-property { color: #FFC66D; }
  .cm-s-default span.cm-operator { color: #A9B7C6; }
  .cm-s-default span.cm-string { color: #6A8759; }
  .cm-s-default span.cm-string-2 { color: #6A8759; }
  .cm-s-default span.cm-comment { color: #61A151; font-style: italic; } 
  .cm-s-default span.cm-link { color: #CC7832; }
  .cm-s-default span.cm-atom { color: #CC7832; }
  .cm-s-default span.cm-error { color: #BC3F3C; }
  .cm-s-default span.cm-tag { color: #629755; font-weight: bold; font-style: italic; text-decoration: underline; }
  .cm-s-default span.cm-attribute { color: #6897bb; }
  .cm-s-default span.cm-qualifier { color: #6A8759; }
  .cm-s-default span.cm-bracket { color: #A9B7C6; }
  .cm-s-default span.cm-builtin { color: #FF9E59; }
  .cm-s-default span.cm-special { color: #FF9E59; }

  .cm-s-default .CodeMirror-cursor { border-left: 1px solid #A9B7C6; }  
  .cm-s-default .CodeMirror-activeline-background { background: #323232; } 
  .cm-s-default .CodeMirror-gutters { background: #313335 !important; border-right: 1px solid #313335 !important; } 
  .cm-s-default .CodeMirror-guttermarker { color: #FFEE80; }  
  .cm-s-default .CodeMirror-guttermarker-subtle { color: #D0D0D0; }  
  .cm-s-default .CodeMirrir-linenumber { color: #606366; } 
  .cm-s-default .CodeMirror-matchingbracket { background-color: #3B514D; color: #FFEF28 !important; font-weight: bold; } 

  .cm-s-default div.CodeMirror-selected { background: #214283; }


  /* AST Explorer Overrides */
  .CodeMirror-hints.default {
    font-family: Menlo, Monaco, Consolas, 'Courier New', monospace;
    color: #9C9E9E;
    background-color: #3B3E3F !important;
  }

  .CodeMirror-hints.default .CodeMirror-hint-active {
    background-color: #494D4E !important;
    color: #9C9E9E !important;
  }

  .output, .toolbar {
    background: #2B2B2B !important; color: #A9B7C6;
    border-color: #555 !important;
  }

  .output .toolbar > button {
    color: white !important;
  }

  .splitpane-divider {
    background-color: #313335 !important;
  }

  #Toolbar, #Toolbar .menuButton ul, #contribution {
      background-color: #313335 !important;
      color: #ddd !important;
      border-color: #555 !important;
  }

  #info a, #contribution a {
    color: #268bd2;
  }

  #info a, #contribution a:visited {
    color: #b9f;
  }

/* DARK THEME */
```
